[assembly: System.Reflection.AssemblyVersion("7.1.0.158")]  // Generated by build
[assembly: System.Reflection.AssemblyInformationalVersion("7.1.0.158")]  // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("7.1.0.163")]  // Generated by build
